// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TmtsChecker.DB;

#nullable disable

namespace TmtsChecker.Migrations
{
    [DbContext(typeof(TmtsDbContext))]
    partial class TmtsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("TmtsChecker.Models.TmHost", b =>
                {
                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hostname");

                    b.ToTable("Hosts");

                    b.HasData(
                        new
                        {
                            Hostname = "PC01",
                            Ip = ""
                        },
                        new
                        {
                            Hostname = "PC02",
                            Ip = ""
                        },
                        new
                        {
                            Hostname = "PC03",
                            Ip = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
